language: android
sudo: required
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_EMULATOR_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMULATOR_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24
  - addon-google_apis-google-27
  #- sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_EMULATOR_LEVEL
  - sys-img-armeabi-v7a-android-24
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache/"
before_script:
- echo "y" | android update sdk -a --no-ui --filter android-24
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-24
- android list targets
- echo no | android create avd --force -n test -t android-24 --abi $ANDROID_ABI
- emulator -avd test -no-window &
- android-wait-for-emulator
script:
- adb shell input keyevent 82 &
- "./gradlew connectedCheck -PdisablePreDex --stacktrace"
- "./gradlew test"
- ./gradlew assemble
- ls -R app/build/outputs/apk
- chmod +x upload.sh
- /bin/sh ./upload.sh

before_install:
- openssl aes-256-cbc -K $encrypted_f9d3779bcad5_key -iv $encrypted_f9d3779bcad5_iv
  -in app/google-services.json.enc -out app/google-services.json -d
