language: android
sudo: required
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=28
  - EMULATOR_LEVEL=24
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$EMULATOR_LEVEL
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_LEVEL
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache/"
before_script:
- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_LEVEL
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_LEVEL
- android list targets
- echo no | android create avd --force -n test -t android-$EMULATOR_LEVEL --abi $ANDROID_ABI
- emulator -avd test -no-window &
- android-wait-for-emulator
script:
- adb shell input keyevent 82 &
- "./gradlew connectedCheck -PdisablePreDex --stacktrace"
- "./gradlew test"
- "./gradlew assembleTravis"
- ls -R app/build/outputs/apk
- chmod +x upload.sh
- "/bin/sh ./upload.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_71632d04a37f_key -iv $encrypted_71632d04a37f_iv
  -in travis-files.tar.enc -out app/travis-files.tar -d
- tar xvf app/travis-files.tar -C app
